spring:

  application:

    name: customer-service

  datasource:

    url: jdbc:mysql://mysql:3306/e_commerce  #if other services on host and mysql in docker, jdbc:mysql://172.18.0.2:3306/e_commerce

    username: root

    password: root
    
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:

    stream:

      bindings:

        OrderEventsChannel:

          destination: OrderEventsChannel

          content-type: application/json

      kafka:

        binder:

            brokers: kafka   #34.131.200.139:9092, if on gcp
