spring:

  application:

    name: order-service

  datasource:

    url: jdbc:mysql://172.18.0.2:3306/e_commerce

    username: root

    password: root

    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:

    show-sql: true

    hibernate.ddl-auto: update

  # cloud:

  #   stream:

  #     bindings:

  #       OrderEventsChannel:

  #         destination: OrderEventsChannel

  #         content-type: application/json

  #         group: OrderEventsChannelQueue

  #     kafka:

  #       binder:

  #         brokers: kafka
